### ISSUE TITLE
revisions.json is empty after deploy

### ISSUE THREAD

**Issue by fsmanuel** [arenoir/ember-cli-deploy-ssh2#11]
@arenoir I'm on a bad internet connection and it seems that the plugin isn't waiting for the tasks to finish. Haven't found the source of the problem but it looks like some of the methods don't return a promise causing ember-cli-deploy to not wait until the work is done. Are you still maintaining the plugin? I would dig into it and send a PR. I think that would solve #8 as well.

**Comment by arenoir** [comment]
@fsmanuel maintaining is subjective. I am using this plugin in production and fix issues that affect my projects. I am short on time and fixing other issues is not a high priority.  That said I would happily accept a pull request. 

Thanks for logging the issue.

**Comment by fsmanuel** [comment]
@arenoir sounds good. I'll open a PR.
