### ISSUE TITLE
Error when adding material design fonts to applicationFiles

### ISSUE THREAD

**Issue by taddeimania** [arenoir/ember-cli-deploy-ssh2#3]
When my `applicationFiles` consists of:

`['index.html', 'assets/gui.css', 'assets/gui.js', 'assets/vendor.css', 'assets/vendor.js']`

But when I add `'font/material-design-icons/Material-Design-Icons.eot'` to the list so it looks like:

`applicationFiles: ['index.html', 'assets/gui.css', 'assets/gui.js', 'assets/vendor.css', 'assets/vendor.js',
      'font/material-design-icons/Material-Design-Icons.eot'],`

I get the following error:

```
- Uploading `applicationFiles` to /var/www/app/revisions/7c33053dff16862be49331bfc02ac39c
/Users/me/Projects/app/frontend/node_modules/ember-cli-deploy-ssh2/lib/ssh-client.js:121
            sftp.fastPut(src, dest, {}, function (err) {
                ^
TypeError: Cannot read property 'fastPut' of undefined
```

**Comment by taddeimania** [comment]
This actually seems to be happening randomly regardless of material design icons.

At one point I ran `ember deploy production` and it ran fine, then immediately ran `ember deploy production --activate` and it failed and now it's continually failing.

**Comment by taddeimania** [comment]
More debugging:

I dumped the error when it fails and I see this:
`{ [Error: (SSH) Channel open failure: open failed] reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }`

**Comment by arenoir** [comment]
@taddeimania 

The `applicationFiles` property is not designed to upload assets. Thus the sub folders won't be created.  Assets are fingerprinted and intended to be put on a cdn or a single directory on a webserver.  

Make sure the `root` directory exists and is readable and writable by the user you are sshing in as. 

I intend to add a way to upload `assets` but for now you could use [rsync](https://github.com/arenoir/ember-cli-deploy-rsync)

**Comment by taddeimania** [comment]
@arenoir Thanks for pointing me towards rsync.  I had reverted to using a shell script to do an ember build and then just scp the assets/index to the server. Glad I don't have to do that anymore.

**Comment by arenoir** [comment]
Issue #4 .
