### ISSUE TITLE
Encrypted private key detected

### ISSUE THREAD

**Issue by basz** [arenoir/ember-cli-deploy-ssh2#5]
hi 

maybe it's me, but i'm getting "Encrypted private key detected, but no passphrase given". 

However I am able to ssh into my server with public key authentication just fine. Why does this plugin use my private key? And why does it have a passphrase? (I wouldn't even know anything other then '').
Can I specify a passphrase, if I have one?

Thanks

**Comment by eighteight** [comment]
+1

**Comment by arenoir** [comment]
I have added the passphrase option.
