### ISSUE TITLE
Activation fails on Windows

### ISSUE THREAD

**Issue by abbec** [arenoir/ember-cli-deploy-ssh2#8]
Running `ember deploy production --activate` on Windows results in the following error. 

```
node_modules\ember-cli-deploy-ssh2\lib\ssh-client.js:59
        var stream = sftp.createWriteStream(path);
                         ^

TypeError: Cannot read property 'createWriteStream' of undefined
    at E:\Code\proj\node_modules\ember-cli-deploy-ssh2\lib\ssh-client.js:59:26
    at E:\Code\proj\node_modules\ssh2\lib\client.js:840:14
    at SSH2Stream.onFailure (E:\Code\proj\node_modules\ssh2\lib\client.js:1177:5)
    at SSH2Stream.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at Socket.<anonymous> (E:\Code\proj\node_modules\ssh2\lib\client.js:320:14)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
```

This seems to be caused by a race condition that causes the ssh client to be disconnected before the manifest upload happens. If I comment out the closing of the connection in `teardown()`, everything works as expected.

**Comment by fsmanuel** [comment]
The same happens on OSX if you have 'too many' files in `applicationFiles`. Right now I have 7 files and it fails. With 6 files it works...

**Comment by arenoir** [comment]
@abbec sorry for taking so long to respond.  I don't have a solution perhaps @fsmnuel has one 😄

**Comment by abbec** [comment]
We are not using this deployment method anymore but thanks for the update! I will close this for now :)
